# Travis continuous integration system configuration file.
# Read more at: http://docs.travis-ci.com/user/customizing-the-build/

sudo: required
dist: xenial
language: node_js
node_js: 11.6.0

git:
  depth: 500
  quiet: true

cache:
  directories:
    - .cached_tools
    - ~/.cache
    - node_modules

before_install:
  - export NG_CLI_ANALYTICS=ci
  - eval "$(gimme 1.12.6)"

jobs:
  include:
    - stage: test
      script: npm run check

stages:
  - test
